;;;; cplusplus-object.import.scm - GENERATED BY CHICKEN 4.8.0.3 -*- Scheme -*-

(eval '(import scheme chicken coops))
(##sys#register-compiled-module
  'cplusplus-object
  (list)
  '((<c++-object> . cplusplus-object#<c++-object>)
    (new . cplusplus-object#new)
    (delete . cplusplus-object#delete)
    (constructor . cplusplus-object#constructor)
    (destructor . cplusplus-object#destructor))
  (list)
  (list))

;; END OF FILE
